### PR TITLE
fix: mw_one is nullptr, but you call his copyDirectoryFiles() function.

### PR DESCRIPTION
**Pull request by GongHeng2017**
Log:
Bug:

### CODE REVIEW

**Comment by GongHeng2017** [comment]
@ic005k

**Comment by GongHeng2017** [comment]
If you working on the debian and add the  sanitize tools, it will crash.

**Comment by GongHeng2017** [comment]
image

**Comment by GongHeng2017** [comment]
on the debian(linux), when the app start, it  is not  first  run the mymain.cpp on "mw_one = mw;"(line 36) ， but run the main.cpp on "mw_one->copyDirectoryFiles();"(line 33).

**Comment by ic005k** [comment]
Running OCAT under Linux, I haven't received any reports from users about any problems with the app yet.
In any case, I will completely refactor it from the program structure and I will take this issue seriously.
Thanks.

**Comment by GongHeng2017** [comment]
Do you have any way of communicating in time? such as WeChat. I would like to know the softwore. I can help you with a little problem.

**Comment by ic005k** [comment]
Sorry, we don't allow any external IMs on the premises we work on, but that's OK, I have an MX Linux here (it's also Debian based) and I'll test it out on it later when I have time. Thanks again.

**Comment by ic005k** [comment]
This is an easy fix, so keep an eye out for subsequent updates to OCAT.

**Comment by ic005k** [comment]
Once again, thank you for your support of OCAT and any suggestions or any questions are welcome.
If you have some free time, you are more than welcome to white box test OCAT.

**Comment by GongHeng2017** [comment]
you are welcome. I do have some leisure time. I want to know about this software from the perspective of developers. For example, those functions are not perfect, and those interactions are not very user-friendly. I wonder if it is convenient for you to communicate?

**Comment by GongHeng2017** [comment]
can you  understand chinese?

**Comment by GongHeng2017** [comment]
> This is an easy fix, so keep an eye out for subsequent updates to OCAT.

This modification is confirmed to be a bit simpler and I can refine it.
You can create a development branch (dev) there, I will submit the code to the dev branch, and you can merge it into the master branch. May I?

**Comment by ic005k** [comment]
> can you understand chinese?

？
当然。

**Comment by ic005k** [comment]
> You can create a development branch (dev) there, I will submit the code to the dev branch, and you can merge it into the master branch. May I?

非常感谢，目前OCAT基本上已经封笔了，剩下的事情就是日常维护和结构代码优化，有时间我就会做这个事情。
如果你在使用的过程中有任何功能需求，可随时告诉我。
目前来说，OCAT的代码总量差不多2万行了，基本上不再接受代码级的PR了，因为OCAT已经非常稳定了，黑盒测试几乎没有任何bug，也经过了大量用户使用（差不多上万的用户）的考验。
无论如何，感谢你的支持。如果时间允许我非常愿意就OCAT的一切与你进行讨论，谢谢。

**Comment by ic005k** [comment]
对了，OCAT的开发模式采用的是非团队模式和敏捷的微迭代方式，可能有很多地方的代码不规范，见谅。

**Comment by GongHeng2017** [comment]
我明白你的意思，功能已经基本封笔，不在做新功能引入；并且测试也完成了，也不会引入新的代码。

**Comment by GongHeng2017** [comment]
如果你方便，可以新拉一个分支，我有时间可以帮忙做一下结构代码优化。

**Comment by ic005k** [comment]
我开了dev分支并打开了Actions，这里：https://github.com/ic005k/OCAuxiliaryTools/tree/dev

**Pull request closed without merging**
