### PR TITLE
OCAT database update

### PR DESCRIPTION
**Pull request by Baio1977**
Thanks for this wonderful application.
I hope I have made a contribution to keeping the application clean and streamlined.

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Keep in mind that some config templates may use some of these specific SSDTS before deleting or renaming them!

**Comment by ic005k** [comment]
> Keep in mind that some config templates may use some of these specific SSDTS before deleting or renaming them!

My bad. I didn't check it carefully. I'm sorry.
In the future, I have decided not to accept any similar PR. Sorry again.

**Comment by Baio1977** [comment]
I deleted double files, too specific files, such as SSDT-PM Ivy Bridge, these are created based on the HW in use.
Then you just need to recall the newly added SSDTs.
See for example config and SSDT for precise Laptop models.
The renames I removed were duplicates or harmful to OC optimizations.
Example renaming EC0 or ECDV to EC in laptops is deleterious.
Better to remove what is not essential or is too personalized.

**Comment by 5T33Z0** [comment]
Your actions ruined some of the Intel configs, because the following SSDTs are now missing:

- SSDT-EC-USBX.aml
- SSDT-AWAC-DISABLE.aml
- SSDT-PMC.aml

**Comment by Baio1977** [comment]
We can fix, as you see now there are new files EC_USBX_Desktop which includes ALL gen HW , SSDT-USBX_Laptop which contains _DSM of apple laptops.
Awac was duplicated so I put in the latest version of SSDT-AWAC , SSDT-PMC has been replaced with SSDT-PMCR.
I'll fix all the various SSDT Config.plist links shortly if that helps

**Comment by 5T33Z0** [comment]
No, that's not necessary. I just fork OCAT myself and then I create a subfolder for all the SSDTs that are used by the base configs so they remain future-proof.

**Pull request merged**
